version: "3.3"
   
services:
  postgres:
    image: postgres:13.4-buster
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
      - ./script/init/postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
        reservations:
          cpus: '0.25'
          memory: 128M  

  mysql:
    image: mysql:8.0.26
    volumes:
      - ./_data/mysql:/var/lib/mysql
      - ./script/init/mysql:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306  
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=psr
      - MYSQL_USER=someone
      - MYSQL_PASSWORD=passme
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
        reservations:
          cpus: '0.25'
          memory: 128M  
    
  generator:
    build: 
      context: ./py
      dockerfile: generator.dockerfile
    volumes:
      - ./py:/usr/src/app
    depends_on:
      - postgres
      - mysql

  consumer:
    environment:
      - CONCURRENCY=8
      - HITS_PER_WORKER=1000
      - TEST_BEHAVIOUR=search # can be search or query
      - TEST_DB=mysql # can be mysql or postgres
      # const env
      - PG_HOST=postgres
      - PG_DB=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - MYSQL_HOST=mysql
      - MYSQL_DB=psr
      - MYSQL_USER=someone
      - MYSQL_PASSWORD=passme


